<?php
// All countries
$countries = array(
	'AF' => array('country_name' => 'Afghanistan','phone_code' => 93),
	'AX' => array('country_name' => 'Aland Islands','phone_code' => 358),
	'AL' => array('country_name' => 'Albania','phone_code' => 355),
	'DZ' => array('country_name' => 'Algeria','phone_code' => 213),
	'AS' => array('country_name' => 'American Samoa','phone_code' => 1684),
	'AD' => array('country_name' => 'Andorra','phone_code' => 376),
	'AO' => array('country_name' => 'Angola','phone_code' => 244),
	'AI' => array('country_name' => 'Anguilla','phone_code' => 1264),
	'AQ' => array('country_name' => 'Antarctica','phone_code' => 672),
	'AG' => array('country_name' => 'Antigua and Barbuda','phone_code' => 1268),
	'AR' => array('country_name' => 'Argentina','phone_code' => 54),
	'AM' => array('country_name' => 'Armenia','phone_code' => 374),
	'AW' => array('country_name' => 'Aruba','phone_code' => 297),
	'AU' => array('country_name' => 'Australia','phone_code' => 61),
	'AT' => array('country_name' => 'Austria','phone_code' => 43),
	'AZ' => array('country_name' => 'Azerbaijan','phone_code' => 994),
	'BS' => array('country_name' => 'Bahamas','phone_code' => 1242),
	'BH' => array('country_name' => 'Bahrain','phone_code' => 973),
	'BD' => array('country_name' => 'Bangladesh','phone_code' => 880),
	'BB' => array('country_name' => 'Barbados','phone_code' => 1246),
	'BY' => array('country_name' => 'Belarus','phone_code' => 375),
	'BE' => array('country_name' => 'Belgium','phone_code' => 32),
	'BZ' => array('country_name' => 'Belize','phone_code' => 501),
	'BJ' => array('country_name' => 'Benin','phone_code' => 229),
	'BM' => array('country_name' => 'Bermuda','phone_code' => 1441),
	'BT' => array('country_name' => 'Bhutan','phone_code' => 975),
	'BO' => array('country_name' => 'Bolivia','phone_code' => 591),
	'BQ' => array('country_name' => 'Bonaire, Sint Eustatius and Saba','phone_code' => 599),
	'BA' => array('country_name' => 'Bosnia and Herzegovina','phone_code' => 387),
	'BW' => array('country_name' => 'Botswana','phone_code' => 267),
	'BV' => array('country_name' => 'Bouvet Island','phone_code' => 55),
	'BR' => array('country_name' => 'Brazil','phone_code' => 55),
	'IO' => array('country_name' => 'British Indian Ocean Territory','phone_code' => 246),
	'BN' => array('country_name' => 'Brunei Darussalam','phone_code' => 673),
	'BG' => array('country_name' => 'Bulgaria','phone_code' => 359),
	'BF' => array('country_name' => 'Burkina Faso','phone_code' => 226),
	'BI' => array('country_name' => 'Burundi','phone_code' => 257),
	'KH' => array('country_name' => 'Cambodia','phone_code' => 855),
	'CM' => array('country_name' => 'Cameroon','phone_code' => 237),
	'CA' => array('country_name' => 'Canada','phone_code' => 1),
	'CV' => array('country_name' => 'Cape Verde','phone_code' => 238),
	'KY' => array('country_name' => 'Cayman Islands','phone_code' => 1345),
	'CF' => array('country_name' => 'Central African Republic','phone_code' => 236),
	'TD' => array('country_name' => 'Chad','phone_code' => 235),
	'CL' => array('country_name' => 'Chile','phone_code' => 56),
	'CN' => array('country_name' => 'China','phone_code' => 86),
	'CX' => array('country_name' => 'Christmas Island','phone_code' => 61),
	'CC' => array('country_name' => 'Cocos (Keeling) Islands','phone_code' => 672),
	'CO' => array('country_name' => 'Colombia','phone_code' => 57),
	'KM' => array('country_name' => 'Comoros','phone_code' => 269),
	'CG' => array('country_name' => 'Congo','phone_code' => 242),
	'CD' => array('country_name' => 'Congo, Democratic Republic of the Congo','phone_code' => 242),
	'CK' => array('country_name' => 'Cook Islands','phone_code' => 682),
	'CR' => array('country_name' => 'Costa Rica','phone_code' => 506),
	'CI' => array('country_name' => 'Cote D\'Ivoire','phone_code' => 225),
	'HR' => array('country_name' => 'Croatia','phone_code' => 385),
	'CU' => array('country_name' => 'Cuba','phone_code' => 53),
	'CW' => array('country_name' => 'Curacao','phone_code' => 599),
	'CY' => array('country_name' => 'Cyprus','phone_code' => 357),
	'CZ' => array('country_name' => 'Czech Republic','phone_code' => 420),
	'DK' => array('country_name' => 'Denmark','phone_code' => 45),
	'DJ' => array('country_name' => 'Djibouti','phone_code' => 253),
	'DM' => array('country_name' => 'Dominica','phone_code' => 1767),
	'DO' => array('country_name' => 'Dominican Republic','phone_code' => 1809),
	'EC' => array('country_name' => 'Ecuador','phone_code' => 593),
	'EG' => array('country_name' => 'Egypt','phone_code' => 20),
	'SV' => array('country_name' => 'El Salvador','phone_code' => 503),
	'GQ' => array('country_name' => 'Equatorial Guinea','phone_code' => 240),
	'ER' => array('country_name' => 'Eritrea','phone_code' => 291),
	'EE' => array('country_name' => 'Estonia','phone_code' => 372),
	'ET' => array('country_name' => 'Ethiopia','phone_code' => 251),
	'FK' => array('country_name' => 'Falkland Islands (Malvinas)','phone_code' => 500),
	'FO' => array('country_name' => 'Faroe Islands','phone_code' => 298),
	'FJ' => array('country_name' => 'Fiji','phone_code' => 679),
	'FI' => array('country_name' => 'Finland','phone_code' => 358),
	'FR' => array('country_name' => 'France','phone_code' => 33),
	'GF' => array('country_name' => 'French Guiana','phone_code' => 594),
	'PF' => array('country_name' => 'French Polynesia','phone_code' => 689),
	'TF' => array('country_name' => 'French Southern Territories','phone_code' => 262),
	'GA' => array('country_name' => 'Gabon','phone_code' => 241),
	'GM' => array('country_name' => 'Gambia','phone_code' => 220),
	'GE' => array('country_name' => 'Georgia','phone_code' => 995),
	'DE' => array('country_name' => 'Germany','phone_code' => 49),
	'GH' => array('country_name' => 'Ghana','phone_code' => 233),
	'GI' => array('country_name' => 'Gibraltar','phone_code' => 350),
	'GR' => array('country_name' => 'Greece','phone_code' => 30),
	'GL' => array('country_name' => 'Greenland','phone_code' => 299),
	'GD' => array('country_name' => 'Grenada','phone_code' => 1473),
	'GP' => array('country_name' => 'Guadeloupe','phone_code' => 590),
	'GU' => array('country_name' => 'Guam','phone_code' => 1671),
	'GT' => array('country_name' => 'Guatemala','phone_code' => 502),
	'GG' => array('country_name' => 'Guernsey','phone_code' => 44),
	'GN' => array('country_name' => 'Guinea','phone_code' => 224),
	'GW' => array('country_name' => 'Guinea-Bissau','phone_code' => 245),
	'GY' => array('country_name' => 'Guyana','phone_code' => 592),
	'HT' => array('country_name' => 'Haiti','phone_code' => 509),
	'HM' => array('country_name' => 'Heard Island and Mcdonald Islands','phone_code' => 0),
	'VA' => array('country_name' => 'Holy See (Vatican City State)','phone_code' => 39),
	'HN' => array('country_name' => 'Honduras','phone_code' => 504),
	'HK' => array('country_name' => 'Hong Kong','phone_code' => 852),
	'HU' => array('country_name' => 'Hungary','phone_code' => 36),
	'IS' => array('country_name' => 'Iceland','phone_code' => 354),
	'IN' => array('country_name' => 'India','phone_code' => 91),
	'ID' => array('country_name' => 'Indonesia','phone_code' => 62),
	'IR' => array('country_name' => 'Iran, Islamic Republic of','phone_code' => 98),
	'IQ' => array('country_name' => 'Iraq','phone_code' => 964),
	'IE' => array('country_name' => 'Ireland','phone_code' => 353),
	'IM' => array('country_name' => 'Isle of Man','phone_code' => 44),
	'IL' => array('country_name' => 'Israel','phone_code' => 972),
	'IT' => array('country_name' => 'Italy','phone_code' => 39),
	'JM' => array('country_name' => 'Jamaica','phone_code' => 1876),
	'JP' => array('country_name' => 'Japan','phone_code' => 81),
	'JE' => array('country_name' => 'Jersey','phone_code' => 44),
	'JO' => array('country_name' => 'Jordan','phone_code' => 962),
	'KZ' => array('country_name' => 'Kazakhstan','phone_code' => 7),
	'KE' => array('country_name' => 'Kenya','phone_code' => 254),
	'KI' => array('country_name' => 'Kiribati','phone_code' => 686),
	'KP' => array('country_name' => 'Korea, Democratic People\'s Republic of','phone_code' => 850),
	'KR' => array('country_name' => 'Korea, Republic of','phone_code' => 82),
	'XK' => array('country_name' => 'Kosovo','phone_code' => 381),
	'KW' => array('country_name' => 'Kuwait','phone_code' => 965),
	'KG' => array('country_name' => 'Kyrgyzstan','phone_code' => 996),
	'LA' => array('country_name' => 'Lao People\'s Democratic Republic','phone_code' => 856),
	'LV' => array('country_name' => 'Latvia','phone_code' => 371),
	'LB' => array('country_name' => 'Lebanon','phone_code' => 961),
	'LS' => array('country_name' => 'Lesotho','phone_code' => 266),
	'LR' => array('country_name' => 'Liberia','phone_code' => 231),
	'LY' => array('country_name' => 'Libyan Arab Jamahiriya','phone_code' => 218),
	'LI' => array('country_name' => 'Liechtenstein','phone_code' => 423),
	'LT' => array('country_name' => 'Lithuania','phone_code' => 370),
	'LU' => array('country_name' => 'Luxembourg','phone_code' => 352),
	'MO' => array('country_name' => 'Macao','phone_code' => 853),
	'MK' => array('country_name' => 'Macedonia, the Former Yugoslav Republic of','phone_code' => 389),
	'MG' => array('country_name' => 'Madagascar','phone_code' => 261),
	'MW' => array('country_name' => 'Malawi','phone_code' => 265),
	'MY' => array('country_name' => 'Malaysia','phone_code' => 60),
	'MV' => array('country_name' => 'Maldives','phone_code' => 960),
	'ML' => array('country_name' => 'Mali','phone_code' => 223),
	'MT' => array('country_name' => 'Malta','phone_code' => 356),
	'MH' => array('country_name' => 'Marshall Islands','phone_code' => 692),
	'MQ' => array('country_name' => 'Martinique','phone_code' => 596),
	'MR' => array('country_name' => 'Mauritania','phone_code' => 222),
	'MU' => array('country_name' => 'Mauritius','phone_code' => 230),
	'YT' => array('country_name' => 'Mayotte','phone_code' => 269),
	'MX' => array('country_name' => 'Mexico','phone_code' => 52),
	'FM' => array('country_name' => 'Micronesia, Federated States of','phone_code' => 691),
	'MD' => array('country_name' => 'Moldova, Republic of','phone_code' => 373),
	'MC' => array('country_name' => 'Monaco','phone_code' => 377),
	'MN' => array('country_name' => 'Mongolia','phone_code' => 976),
	'ME' => array('country_name' => 'Montenegro','phone_code' => 382),
	'MS' => array('country_name' => 'Montserrat','phone_code' => 1664),
	'MA' => array('country_name' => 'Morocco','phone_code' => 212),
	'MZ' => array('country_name' => 'Mozambique','phone_code' => 258),
	'MM' => array('country_name' => 'Myanmar','phone_code' => 95),
	'NA' => array('country_name' => 'Namibia','phone_code' => 264),
	'NR' => array('country_name' => 'Nauru','phone_code' => 674),
	'NP' => array('country_name' => 'Nepal','phone_code' => 977),
	'NL' => array('country_name' => 'Netherlands','phone_code' => 31),
	'AN' => array('country_name' => 'Netherlands Antilles','phone_code' => 599),
	'NC' => array('country_name' => 'New Caledonia','phone_code' => 687),
	'NZ' => array('country_name' => 'New Zealand','phone_code' => 64),
	'NI' => array('country_name' => 'Nicaragua','phone_code' => 505),
	'NE' => array('country_name' => 'Niger','phone_code' => 227),
	'NG' => array('country_name' => 'Nigeria','phone_code' => 234),
	'NU' => array('country_name' => 'Niue','phone_code' => 683),
	'NF' => array('country_name' => 'Norfolk Island','phone_code' => 672),
	'MP' => array('country_name' => 'Northern Mariana Islands','phone_code' => 1670),
	'NO' => array('country_name' => 'Norway','phone_code' => 47),
	'OM' => array('country_name' => 'Oman','phone_code' => 968),
	'PK' => array('country_name' => 'Pakistan','phone_code' => 92),
	'PW' => array('country_name' => 'Palau','phone_code' => 680),
	'PS' => array('country_name' => 'Palestinian Territory, Occupied','phone_code' => 970),
	'PA' => array('country_name' => 'Panama','phone_code' => 507),
	'PG' => array('country_name' => 'Papua New Guinea','phone_code' => 675),
	'PY' => array('country_name' => 'Paraguay','phone_code' => 595),
	'PE' => array('country_name' => 'Peru','phone_code' => 51),
	'PH' => array('country_name' => 'Philippines','phone_code' => 63),
	'PN' => array('country_name' => 'Pitcairn','phone_code' => 64),
	'PL' => array('country_name' => 'Poland','phone_code' => 48),
	'PT' => array('country_name' => 'Portugal','phone_code' => 351),
	'PR' => array('country_name' => 'Puerto Rico','phone_code' => 1787),
	'QA' => array('country_name' => 'Qatar','phone_code' => 974),
	'RE' => array('country_name' => 'Reunion','phone_code' => 262),
	'RO' => array('country_name' => 'Romania','phone_code' => 40),
	'RU' => array('country_name' => 'Russian Federation','phone_code' => 70),
	'RW' => array('country_name' => 'Rwanda','phone_code' => 250),
	'BL' => array('country_name' => 'Saint Barthelemy','phone_code' => 590),
	'SH' => array('country_name' => 'Saint Helena','phone_code' => 290),
	'KN' => array('country_name' => 'Saint Kitts and Nevis','phone_code' => 1869),
	'LC' => array('country_name' => 'Saint Lucia','phone_code' => 1758),
	'MF' => array('country_name' => 'Saint Martin','phone_code' => 590),
	'PM' => array('country_name' => 'Saint Pierre and Miquelon','phone_code' => 508),
	'VC' => array('country_name' => 'Saint Vincent and the Grenadines','phone_code' => 1784),
	'WS' => array('country_name' => 'Samoa','phone_code' => 684),
	'SM' => array('country_name' => 'San Marino','phone_code' => 378),
	'ST' => array('country_name' => 'Sao Tome and Principe','phone_code' => 239),
	'SA' => array('country_name' => 'Saudi Arabia','phone_code' => 966),
	'SN' => array('country_name' => 'Senegal','phone_code' => 221),
	'RS' => array('country_name' => 'Serbia','phone_code' => 381),
	'CS' => array('country_name' => 'Serbia and Montenegro','phone_code' => 381),
	'SC' => array('country_name' => 'Seychelles','phone_code' => 248),
	'SL' => array('country_name' => 'Sierra Leone','phone_code' => 232),
	'SG' => array('country_name' => 'Singapore','phone_code' => 65),
	'SX' => array('country_name' => 'Sint Maarten','phone_code' => 1),
	'SK' => array('country_name' => 'Slovakia','phone_code' => 421),
	'SI' => array('country_name' => 'Slovenia','phone_code' => 386),
	'SB' => array('country_name' => 'Solomon Islands','phone_code' => 677),
	'SO' => array('country_name' => 'Somalia','phone_code' => 252),
	'ZA' => array('country_name' => 'South Africa','phone_code' => 27),
	'GS' => array('country_name' => 'South Georgia and the South Sandwich Islands','phone_code' => 500),
	'SS' => array('country_name' => 'South Sudan','phone_code' => 211),
	'ES' => array('country_name' => 'Spain','phone_code' => 34),
	'LK' => array('country_name' => 'Sri Lanka','phone_code' => 94),
	'SD' => array('country_name' => 'Sudan','phone_code' => 249),
	'SR' => array('country_name' => 'Suriname','phone_code' => 597),
	'SJ' => array('country_name' => 'Svalbard and Jan Mayen','phone_code' => 47),
	'SZ' => array('country_name' => 'Swaziland','phone_code' => 268),
	'SE' => array('country_name' => 'Sweden','phone_code' => 46),
	'CH' => array('country_name' => 'Switzerland','phone_code' => 41),
	'SY' => array('country_name' => 'Syrian Arab Republic','phone_code' => 963),
	'TW' => array('country_name' => 'Taiwan, Province of China','phone_code' => 886),
	'TJ' => array('country_name' => 'Tajikistan','phone_code' => 992),
	'TZ' => array('country_name' => 'Tanzania, United Republic of','phone_code' => 255),
	'TH' => array('country_name' => 'Thailand','phone_code' => 66),
	'TL' => array('country_name' => 'Timor-Leste','phone_code' => 670),
	'TG' => array('country_name' => 'Togo','phone_code' => 228),
	'TK' => array('country_name' => 'Tokelau','phone_code' => 690),
	'TO' => array('country_name' => 'Tonga','phone_code' => 676),
	'TT' => array('country_name' => 'Trinidad and Tobago','phone_code' => 1868),
	'TN' => array('country_name' => 'Tunisia','phone_code' => 216),
	'TR' => array('country_name' => 'Turkey','phone_code' => 90),
	'TM' => array('country_name' => 'Turkmenistan','phone_code' => 7370),
	'TC' => array('country_name' => 'Turks and Caicos Islands','phone_code' => 1649),
	'TV' => array('country_name' => 'Tuvalu','phone_code' => 688),
	'UG' => array('country_name' => 'Uganda','phone_code' => 256),
	'UA' => array('country_name' => 'Ukraine','phone_code' => 380),
	'AE' => array('country_name' => 'United Arab Emirates','phone_code' => 971),
	'GB' => array('country_name' => 'United Kingdom','phone_code' => 44),
	'US' => array('country_name' => 'United States','phone_code' => 1),
	'UM' => array('country_name' => 'United States Minor Outlying Islands','phone_code' => 1),
	'UY' => array('country_name' => 'Uruguay','phone_code' => 598),
	'UZ' => array('country_name' => 'Uzbekistan','phone_code' => 998),
	'VU' => array('country_name' => 'Vanuatu','phone_code' => 678),
	'VE' => array('country_name' => 'Venezuela','phone_code' => 58),
	'VN' => array('country_name' => 'Viet Nam','phone_code' => 84),
	'VG' => array('country_name' => 'Virgin Islands, British','phone_code' => 1284),
	'VI' => array('country_name' => 'Virgin Islands, U.s.','phone_code' => 1340),
	'WF' => array('country_name' => 'Wallis and Futuna','phone_code' => 681),
	'EH' => array('country_name' => 'Western Sahara','phone_code' => 212),
	'YE' => array('country_name' => 'Yemen','phone_code' => 967),
	'ZM' => array('country_name' => 'Zambia','phone_code' => 260),
	'ZW' => array('country_name' => 'Zimbabwe','phone_code' => 263)
);
?>